name: Generate contribution snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: write

    steps:
      - name: Generate snake SVGs
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-grid-snake-p3r-blue-v2.svg?color_snake=#00CFFF&color_dots=#EAFBFF,#A5F1FF,#42DFFF,#078CE5,#092DBD
            dist/github-contribution-grid-snake-p3r-blue-v2-dark.svg?color_snake=#24E7EA&color_dots=#071A52,#093B9F,#0757D8,#078CE5,#24E7EA

      - name: Publish to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          build_dir: dist
          target_branch: output
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
